import os

active_findings_markdown_summary_template = """DefectDojo active findings summary for {0}
* Total: {1}
* Critical: {2}
* High: {3}
* Medium: {4}
* Low: {5}
* Info: {6}

Generated by: defectdojo-active-findings from portswigger-cloud
:sauropod:
"""


def set_action_outputs(output_pairs: dict):
    if "GITHUB_OUTPUT" in os.environ:
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            for key, value in output_pairs.items():
                print("{0}={1}".format(key, value), file=f)


def active_findings_markdown_step_summary(
    product,
    total,
    critical,
    high,
    medium,
    low,
    info,
):
    if "GITHUB_STEP_SUMMARY" in os.environ:
        with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as f:
            print(
                active_findings_markdown_summary_template.format(
                    product,
                    total,
                    critical,
                    high,
                    medium,
                    low,
                    info,
                ),
                file=f,
            )
