name: static tests
on:
  - push

jobs:
  semgrep-sast-scan:
    name: semgrep sast scan
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
      - name: semgrep scan
        id: semgrep-scan
        run: |
          mkdir -p semgrep/results
          semgrep --config auto --error --json --output=semgrep/results/semgrep.json
      - name: upload semgrep results
        id: upload-semgrep-results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-results
          path: semgrep/results/

  pytest:
    name: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      checks: write
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v3
      - name: set-up-python ${{ matrix.python-version }}
        id: set-up-python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: install python dependencies
        id: install-python-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: test
        run: |
          tox
      - name: publish pytest report
        id: publish-pytest-report
        if: always()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: reports/unit-test-*.xml
          require_tests: true
      - name: upload pytest-cov report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-cov-report
          path: reports/*pytest-cov*